### ISSUE TITLE
AttributeError: module 'config' has no attribute 'cid'

### ISSUE THREAD

**Issue by thetejasmagade** [shreyaspj20/Music-recommendation-system#3]
Hello, @shreyaspj20 

There was an error in code. please help me to solve this. why it is saying _**module 'config' has no attribute 'cid'**_

> Traceback (most recent call last):
  File ".\run.py", line 15, in <module>
    client_credentials_manager = SpotifyClientCredentials(client_id=config.cid, client_secret=config.secret)
AttributeError: module 'config' has no attribute 'cid'

**Comment by angley21** [comment]
> Hello, @shreyaspj20
> 
> There was an error in code. please help me to solve this. why it is saying _**module 'config' has no attribute 'cid'**_
> 
> > Traceback (most recent call last):
> > File ".\run.py", line 15, in 
> > client_credentials_manager = SpotifyClientCredentials(client_id=config.cid, client_secret=config.secret)
> > AttributeError: module 'config' has no attribute 'cid'

you can remove the line **import config** and give your own Spotify client details like so, found it much feasible:

> client_id = ""
> client_secret = ""
> client_credentials_manager = SpotifyClientCredentials(client_id=client_id, client_secret=client_secret)
> sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

**Comment by thetejasmagade** [comment]
@shreyaspj20 bro Thanks it's working fine now ❤️❤️
